name: Palomar Preflight

on:
  push:
    branches: [palomar]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  palomar-preflight:
    uses: PalomarRegistry/PalomarSubmission/.github/workflows/submission.yml@e48a86d0495356b5131a92c9406aa6e27cf99e56
    with:
      repository: ${{ github.repository }}
      commit: ${{ github.sha }}
      pipeline_commit: e48a86d0495356b5131a92c9406aa6e27cf99e56
      request_id: petersenzf01
      mode: full
      execution_profile: palomar-standard-v1
      options: '{"comparator_config_path":"comparator.json","authorization_relationship":"I am a responsible author or maintainer"}'
